version: "3.9"

services:
  app:
    build:
      args:
        user: $USER
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: univasf-mobile-backend-app
    environment:
      - TZ=America/Recife
    restart: unless-stopped
    working_dir: /var/www
    tty: true
    volumes:
      - "./:/var/www"
    depends_on:
      - db
    networks:
      - univasf-mobile

  nginx:
    image: nginx:1.25.0-alpine
    container_name: univasf-mobile-backend-nginx
    restart: unless-stopped
    tty: true
    env_file:
      - ./.env
    environment:
      TIMEZONE: America/Recife
    volumes:
      - "./:/var/www"
      - "./.docker/nginx/${APP_ENV}.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8000:80"
      - "8443:443"
    depends_on:
      - app
    networks:
      - univasf-mobile

  db:
    container_name: univasf-mobile-backend-db
    image: postgres:15-alpine
    restart: unless-stopped
    tty: true
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ".docker/postgres/data:/var/lib/postgresql/data"
    networks:
      - univasf-mobile

networks:
  univasf-mobile:
    driver: bridge
